version: '3.8'

services:
  pricing-engine:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: pricing-engine
    # Streamlit app runs on 8501 internally, no need to expose to host directly
    # ports:
    #   - "8501:8501"
    volumes:
      - ./pricing_engine.db:/app/pricing_engine.db
    command: streamlit run Welcome.py --server.port=8501 --server.address=0.0.0.0

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pricing-engine
